import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Silvia Rinetti',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col p-24">
          <nav>
            <a href='/'>Home</a>
            <a href='/contact'>Contact</a>
            <a href='/cita-previa'>Pide cita</a>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
